export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const SET_CURRENT_MODAL_CONTENT = "SET_CURRENT_MODAL_CONTENT";

export const SET_DISPLAYED_ITEM_IN_VIEW = "SET_DISPLAYED_ITEM_IN_VIEW";
export const SET_DISPLAYED_ITEM_TYPE_IN_VIEW = "SET_DISPLAYED_ITEM_TYPE_IN_VIEW";
export const DISPLAY_ITEM = "DISPLAY_ITEM";

export const SET_DISPLAYED_ITEM_IN_PROJECTVIEW = "SET_DISPLAYED_ITEM_IN_PROJECTVIEW";
export const DISPLAY_PROJECTITEM = "DISPLAY_PROJECTITEM";
